release: v0.0.6

diff --git a/mynetwork/Dockerfile b/mynetwork/Dockerfile
--- a/mynetwork/Dockerfile
+++ b/mynetwork/Dockerfile
@@ -1,7 +1,10 @@
-ARG BUILD_FROM=ghcr.io/erreur32/mynetwork:0.0.5
+ARG BUILD_FROM=ghcr.io/erreur32/mynetwork:0.0.6
 FROM ${BUILD_FROM}
 
-# jq to read /app/data/options.json (Supervisor)
+# Fail build if base image is missing app (e.g. wrong tag or incomplete image)
+RUN test -f /app/server/index.ts && test -x /app/node_modules/.bin/tsx || (echo "FATAL: base image must have /app/server and /app/node_modules (use ghcr.io/erreur32/mynetwork:TAG from https://github.com/Erreur32/MynetworK)" && exit 1)
+
+# jq to read /data/options.json (Supervisor)
 RUN apk add --no-cache jq
 
 COPY run.sh /run.sh
